### ISSUE TITLE
<color> tag doesn't apply until after text fades in

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-dlls#14]
![tsukiredtext](https://user-images.githubusercontent.com/20390474/39105083-9ed3f388-4681-11e8-8826-0b73ff712de3.png)

`<color=#ff0000>Blah blah blah.</color>`

The color tag allows text to get drawn in a specific color.  We currently use this on the nametags, but I ran into a problem when I tried using it on actual in-game text.  The text stays white while it fades in, and it only applies the color effect after the text has completely faded in.  This causes a weird effect where the leading edge of the text is white as it gets drawn.

It actually looks kinda cool, but it's really distracting.

**Comment by ghost** [comment]
Alright I found out why this is happening.  The game is not using TextMeshPro to do it - instead it's passing the whole text buffer to it at once but also it's doing this script-level hack to make the fade-in work properly, and it's **tied to the white color**. So if a snippet of the current text on screen is `abcd` that actually gets passed from the game to textmeshpro as  `<#FFFFFF00>a<#FFFFFF00>b<#FFFFFF00>c<#FFFFFF00>d` and each character's `00`s will eventually increase until it's done fading in and then it removes the hacky tag in front of that character, at which point your original `<color=#ff0000>` tag from earlier takes over.  It's literally rewriting the current text every frame or whatever.

There's no way to do this with just the alpha with the textmeshpro tags[0], so i'm gonna follow the code example in [1] to do it through TMP with each character's corresponding TextInfo's alpha attribute.  Cause the other way would involve re-parsing the color tags in each line and hacking that hack to be color-agnostic, so i'm going to try to not do that if at all possible.

[0] http://digitalnativestudios.com/textmeshpro/docs/ScriptReference/RichTags.html
[1] http://digitalnativestudios.com/forum/index.php?topic=1182.msg8986#msg8986

**Comment by ghost** [comment]
Turns out rich tags do support color-independent alpha tags.   I just had to look at the newer script reference.

http://digitalnativestudios.com/textmeshpro/docs/rich-text/#color

I tested it real quick with ADV mode and it worked.  Pushed in https://github.com/07th-mod/higurashi-assembly/commit/c45b8c521cba7daa8aecc54a2f410ac6653448a3 on the mod branch.  @DoctorDiablo can you test this out when you get a chance?  This branches off of Oni, but if you needed, I can make a console arcs branch with that cherry-picked commit - it would be no trouble.

**Comment by ghost** [comment]
Confirmed working by @DoctorDiablo
