### ISSUE TITLE
Separate save directory for console arcs

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-dlls#17]
Currently the console arcs share their save directory with Himatsubushi (if you have 2 Hima installations).

We should make the console arcs use their own directory for the save files.

The save path might be a good thing to add into JSON config file if we add one.

**Comment by ghost** [comment]
I'm thinking at this point I will probably implement this via #19

**Comment by enumag** [comment]
@idealpersona Indeed that would be the best. 👍

**Comment by ghost** [comment]
This is implemented via #19 using the config string `SaveSubdirectory`.  Look at that issue for more info.

When present, the game will look to the given subdirectory within the default save directory for both save files and global.dat.  Global.dat was a side-effect, not intentional, but it appears to be okay.

Once this looks stable it will be merged to master.

**Comment by ghost** [comment]
@DoctorDiablo This is now ready for you in the `config` branch for hima. Check out this thread and issue 19 and let me know if you need any assistance.

**Comment by DoctorDiablo** [comment]
Fixed as of 784f2519d59c889e730b9b9eecda28d897a978c5
